apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: java-springboot
  title: Java Spring Boot Service
  description: Generates a Spring Boot service with standard workflows, infra, and editor settings.
  tags: [java, spring, springboot]
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Project
      required:
        - project_name
        - template_name
      properties:
        project_name:
          title: Project Name
          type: string
          description: The name of the project.
          ui:autofocus: true
          minLength: 1

        template_name:
          title: Project Template
          type: string
          description: The name of the template that will be used to bootstrap your project.
          enum:
            - java-springboot
            - react
          enumNames:
            - Java Spring Boot
            - React

    - title: OpenShift / ECP
      required:
        - openshift_cluster
        - openshift_namespace
        - openshift_token
      properties:
        openshift_cluster:
          title: OpenShift Cluster
          type: string
          description: The Kubernetes/OpenShift environment where your apps run.
          minLength: 1

        openshift_namespace:
          title: OpenShift Namespace
          type: string
          description: >
            The logical folder inside a cluster that isolates resources (apps, services, secrets, configs)
            for a team or project.
          minLength: 1

        openshift_token:
          title: ECP Token
          type: string
          description: The credential used to authenticate to the cluster's API (like an access key).
          ui:widget: password
          minLength: 1

  steps:
    - id: fetch
      name: Fetch skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          project_name: ${{ parameters.project_name }}
          template_name: ${{ parameters.template_name }}
          openshift_cluster: ${{ parameters.openshift_cluster }}
          openshift_namespace: ${{ parameters.openshift_namespace }}
          openshift_token: ${{ parameters.openshift_token }}

          # Convenience values
          proj_name_kebab: ${{ parameters.project_name | lower | replace(" ", "-") }}
          proj_name_snake: ${{ parameters.project_name | lower | replace(" ", "_") }}
          proj_name_pascal: ${{ parameters.project_name
            | replace("-", " ")
            | replace("_", " ")
            | title
            | replace(" ", "")
          }}          

        # If workflow files get mangled because of `${{ ... }}` collisions, uncomment:
        # copyWithoutTemplating:
        #   - .github/workflows/*.yml
        #   - .github/workflows/*.yaml

    - id: rename
      name: Rename project folders/files
      action: fs:rename
      input:
        files:
          # main package folder
          - from: src/main/java/gov/irs/app
            to: src/main/java/gov/irs/${{ parameters.project_name | lower | replace("-", "_") | replace(" ", "_") }}

          # test package folder
          - from: src/test/java/gov/irs/app
            to: src/test/java/gov/irs/${{ parameters.project_name | lower | replace("-", "_") | replace(" ", "_") }}

          # main application class filename (path updated because folder moved)
          - from: src/main/java/gov/irs/${{ parameters.project_name | lower | replace("-", "_") | replace(" ", "_") }}/Application.java
            to: src/main/java/gov/irs/${{ parameters.project_name | lower | replace("-", "_") | replace(" ", "_") }}/${{ parameters.project_name | lower | replace("-", "_") | replace(" ", "_") }}Application.java

    - id: publish
      name: Publish to GitHub (tpharrison)
      action: publish:github
      input:
        # Creates: https://github.com/tpharrison/<project_name>
        repoUrl: github.com?owner=tpharrison&repo=${{ parameters.project_name }}
        description: ${{ parameters.project_name }}
        defaultBranch: main

    - id: register
      name: Register in RHDH catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
